name: surrealdb_todo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  surrealdb: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.1.5
  custom_lint: ^0.3.2
  riverpod_generator: ^2.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
